# Generated by Django 4.1.5 on 2023-02-10 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('designation', models.CharField(max_length=50,verbose_name='Designation')),
                ('section', models.CharField(max_length=50,verbose_name='Section')),
            ],
        ),
    ]
