# Generated by Django 4.1.5 on 2023-02-11 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0003_database2_delete_designation_alter_database_section'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DataBase2',
        ),
    ]
